after_script:
  - docker images

before_script:
  - cd "$VERSION"
  - IMAGE="litecoin-core:${VERSION/\//-}"

env:
  - VERSION=0.14
  - VERSION=0.14/alpine
  - VERSION=0.13
  - VERSION=0.13/alpine
  - VERSION=0.12
  - VERSION=0.12/alpine
  - VERSION=0.11
  - VERSION=0.11/alpine

language: bash

script:
  - docker build -t "$IMAGE" .
  - docker run "$IMAGE" --version | grep "Litecoin Core"

services: docker
