after_script:
  - docker images

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce=17.05.0~ce-0~ubuntu-trusty

before_script:
  - cd "$VERSION"
  - IMAGE="litecoin-core:${VERSION/\//-}"

env:
  - VERSION=0.14
  - VERSION=0.14/alpine
  - VERSION=0.13
  - VERSION=0.13/alpine
  - VERSION=0.10
  - VERSION=0.10/alpine

language: bash

script:
  - docker build -t "$IMAGE" .
  - docker run "$IMAGE" --version | grep "Litecoin"

services: docker
